ALTER TABLE `krrtfir_rtfund`.`ATN_requests` MODIFY COLUMN `ConfirmExtra`
INTEGER UNSIGNED NOT NULL DEFAULT 0,
 ADD COLUMN `RealExtra` INTEGER UNSIGNED NOT NULL AFTER `IsArchive`,
 ADD COLUMN `LegalExtra` INTEGER UNSIGNED NOT NULL AFTER `RealExtra`;

 ALTER TABLE `krrtfir_rtfund`.`ATN_requests` MODIFY COLUMN `RealExtra` INTEGER UNSIGNED NOT NULL DEFAULT 0,
 MODIFY COLUMN `LegalExtra` INTEGER UNSIGNED NOT NULL DEFAULT 0;
